imagePullSecrets:
  - name: ghcr-pull
customSelectorLabels:
  app: "slipbox"
image:
  repository: "ghcr.io/dfgh012316/slipbox"
  tag: "cd2ae67"
ingress:
  enabled: false
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi
probes:
  liveness:
    path: /health
    initialDelaySeconds: 30
  readiness:
    path: /health
    initialDelaySeconds: 10
environment: "prod"
configMap:
  enabled: true
  data:
    REDIRECT_URI: "https://slipbox.jerrytech.me/api/auth/google/callback"
    FRONTEND_URL: ""
secret:
  enabled: true
migrations:
  enabled: true
