imagePullSecrets:
  - name: ghcr-pull
customSelectorLabels:
  app: "slipkit"
image:
  repository: "ghcr.io/dfgh012316/slipkit"
  tag: "23583a6"
ingress:
  enabled: false
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi
environment: "prod"
configMap:
  enabled: true
  data:
    REDIRECT_URI: "https://slipkit.jerrytech.me/api/auth/google/callback"
    FRONTEND_URL: ""
secret:
  enabled: true
migrations:
  enabled: true
