customSelectorLabels:
  app: "popofinder"
image:
  repository: "dfgh012316/popofinder"
  tag: "d8e8ba8"
ingress:
  enabled: false
configMap:
  enabled: true
  data:
    ENVIRONMENT: "production"
    DB_NAME: "popo"
    DB_USER: "postgres"
